"""Generate boot_keys.c (MCUboot verify public key) from the signing PEM.

Produces the complete translation unit expected by bootutil:
bootutil_keys[] wrapper + rsa_pub_key[] (RSA public key, PKCS#1 DER)
+ rsa_pub_key_len, so the embedded key always matches the key that
signed fw.signed.bin (single source of truth: tools/keys/*.pem).

Usage: python tools/gen_boot_keys.py <pem> <out.c>
"""
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

HEADER = '''\
/*
 * Copyright (c) 2026 Kabirz.
 * SPDX-License-Identifier: Apache-2.0
 *
 * MCUboot 验签公钥 (RSA-2048 PKCS#1 DER)。构建时由
 * tools/gen_boot_keys.py 从签名私钥 pem 自动生成到构建目录,
 * 与 fw.signed.bin 的签名密钥保证配对。
 */

#include <bootutil/sign_key.h>
#include <mcuboot_config/mcuboot_config.h>

extern const unsigned char rsa_pub_key[];
extern const unsigned int rsa_pub_key_len;

const struct bootutil_key bootutil_keys[] = {
    {
        .key = rsa_pub_key,
        .len = &rsa_pub_key_len,
    },
};
const int bootutil_key_cnt = 1;

/* Autogenerated by tools/gen_boot_keys.py -- do not edit. */
'''


def main():
    pem, out = sys.argv[1], sys.argv[2]
    key = serialization.load_pem_private_key(open(pem, 'rb').read(),
                                             password=None)
    pub = key.public_key().public_bytes(Encoding.DER, PublicFormat.PKCS1)
    with open(out, 'w', newline='\n') as f:
        f.write(HEADER)
        f.write('const unsigned char rsa_pub_key[] = {\n')
        for i in range(0, len(pub), 8):
            f.write('    ' + ', '.join('0x%02x' % b for b in pub[i:i + 8])
                    + ',\n')
        f.write('};\n')
        f.write('const unsigned int rsa_pub_key_len = %d;\n' % len(pub))
    print('rsa_pub_key: %d bytes' % len(pub))


if __name__ == '__main__':
    main()
