"""Generate fw_keyhash.h (compile-time keyhash) from the signing PEM.

keyhash = SHA-256(RSA public key, PKCS#1 DER) -- identical to the
IMG_TLV_KEYHASH value imgtool bakes into signed images (MCUboot
computes the same over the embedded public key at verify time).

Usage: python tools/gen_keyhash.py <pem> <out.h>
"""
import hashlib
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat


def main():
    pem, out = sys.argv[1], sys.argv[2]
    key = serialization.load_pem_private_key(open(pem, 'rb').read(),
                                             password=None)
    pub = key.public_key().public_bytes(Encoding.DER, PublicFormat.PKCS1)
    kh = hashlib.sha256(pub).digest()
    with open(out, 'w', newline='\n') as f:
        f.write('/* Autogenerated by tools/gen_keyhash.py -- do not edit. */\n')
        f.write('#ifndef FW_KEYHASH_H\n#define FW_KEYHASH_H\n\n')
        f.write('static const unsigned char fw_keyhash[32] = {\n    ')
        f.write(', '.join('0x%02x' % b for b in kh))
        f.write(',\n};\n\n#endif /* FW_KEYHASH_H */\n')


if __name__ == '__main__':
    main()
