"""Regenerate the MCUboot signing keypair.

  python tools/gen_keys.py            # default tools/keys/root-rsa2048.pem

Outputs the RSA-2048 PEM. The verify public key (boot_keys.c) is now
generated at build time from the PEM by CMake (tools/gen_boot_keys.py),
so after regenerating only boot + app must be reflashed via SWD.
"""
import os
import subprocess
import sys
import sysconfig

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def imgtool():
    exe = os.path.join(sysconfig.get_path('scripts'), 'imgtool.exe')
    if not os.path.exists(exe):
        exe = os.path.join(sysconfig.get_path('scripts'), 'imgtool')
    return exe


def main():
    pem = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        ROOT, 'tools', 'keys', 'root-rsa2048.pem')
    subprocess.check_call([imgtool(), 'keygen', '-k', pem, '-t', 'rsa-2048'])
    print('pem:', pem)
    print('boot_keys.c is regenerated by cmake at build time;'
          ' rebuild and reflash boot+app')


if __name__ == '__main__':
    main()
